/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/games/{gameId}/abandoned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Game service notifies matchmaking that a tournament game was abandoned. */
        post: operations["MatchmakingService_gameAbandoned"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/games/{gameId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Game service sends result when game completes. Matchmaking routes to appropriate manager (custom/queue/tournament) via GameRegistry. */
        post: operations["MatchmakingService_gameComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GameResultWebhookBody: {
            players: {
                /** Format: uint64 */
                id: number;
                /** Format: int32 */
                score: number;
            }[];
            /**
             * Format: uint64
             * @description Winner ID. Optional for classic games (draws allowed), but tournament games must have a winner.
             */
            winnerId?: number;
            /** Format: date-time */
            date: string;
            /** Format: duration */
            duration: string;
        };
        TournamentGameAbandonedWebhookBody: {
            connectedPlayers?: number[];
        };
        WebhookResponse: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MatchmakingService_gameAbandoned: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentGameAbandonedWebhookBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    MatchmakingService_gameComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameResultWebhookBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
}
